[project]
name = "build-iphone3-0-sdk-headers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygit2>=1.18.0",
    "pyyaml>=6.0.2",
]
