name: Build common 3.0 SDK

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Create SDK
      run: cmake --install ${{github.workspace}}/build

    - name: Bundle SDK
      run: tar -czf common-3.0.sdk.tar.gz common-3.0.sdk/

    - uses: actions/upload-artifact@v4
      with:
        name: common-3.0-sdk
        path: common-3.0.sdk

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: common-3.0.sdk.tar.gz
