name: Build iPhoneOS3.0 custom SDK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Create SDK
      run: cmake --install ${{github.workspace}}/build

    - name: Bundle SDK
      run: tar -czf iPhoneOS3.0-custom.sdk.tar.gz iPhoneOS3.0-custom.sdk/

    - uses: actions/upload-artifact@v4
      with:
        name: iPhoneOS3.0-custom-sdk
        path: iPhoneOS3.0-custom.sdk.tar.gz
